##
## EPITECH PROJECT, 2023
## src
## File description:
## Makefile
##

SRCS := $(wildcard *.c)
OBJS := $(SRCS:.c=.o)
DIRS := $(shell find . -mindepth 1 -maxdepth 1 -type d)

include $(SUB_MAKE_INCLUDE)
